version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: ${DOCKER_RESTART:-always}
    expose:
      - "3306"
    volumes:
      - vdb:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE:-wpdb}"
      MYSQL_USER: "${MYSQL_USER:-wpuser}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-wppass}"
      MYSQL_RANDOM_ROOT_PASSWORD: "1"

  wp:
    image: wordpress:5.7.2-php7.4-fpm
    restart: ${DOCKER_RESTART:-always}
    expose:
      - "9000"
    volumes:
      - vwp:/var/www/html
    depends_on:
      - db
    links:
      - db:mysql-host
    environment:
      WORDPRESS_DB_HOST: "mysql-host"
      WORDPRESS_DB_USER: "${MYSQL_USER:-wpuser}"
      WORDPRESS_DB_PASSWORD: "${MYSQL_PASSWORD:-wppass}"
      WORDPRESS_DB_NAME: "${MYSQL_DATABASE:-wpdb}"

  proxy:
    build:
      dockerfile: nginx.Dockerfile
      context: .
    ports:
      - "${HOST_PORT}80"
    depends_on:
      - wp
    links:
      - wp:wp-host
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - vwp:/var/www/html
    extra_hosts:
      - "${WORDPRESS_DOMAIN:-localhost}:127.0.0.1"
    environment:
      VIRTUAL_HOST: "${WORDPRESS_DOMAIN:-localhost}"
      VIRTUAL_PORT: 80
 
volumes:
  vwp:
  vdb:

networks:
  default:
    external:
      name: nginx-gateway

